lines = []
a = lines.append

a('<p align="center">')
a('  <img src="docs/images/hero_banner.png" alt="TinyTPU" width="100%">')
a('</p>')
a('')
a('<h3 align="center">Production Edge AI for Robots Without GPUs</h3>')
a('')
a('<p align="center">')
a('  <em>From silicon architecture to safety-certified robot control in one framework.</em><br>')
a('  <em>Auto-configures to your hardware. 26 Hz control from 2 FPS vision. Zero-config deployment.</em>')
a('</p>')
a('')
a('<p align="center">')
a('  <img src="https://img.shields.io/badge/python-3.8%2B-blue" alt="Python">')
a('  <img src="https://img.shields.io/badge/tests-161%20passed-brightgreen" alt="Tests">')
a('  <img src="https://img.shields.io/badge/license-MIT-green" alt="License">')
a('  <img src="https://img.shields.io/badge/platforms-x86%20%7C%20ARM%20%7C%20Pi-orange" alt="Platforms">')
a('</p>')
a('')
a('<p align="center">')
a('  <a href="#quick-start">Quick Start</a> &bull;')
a('  <a href="#architecture">Architecture</a> &bull;')
a('  <a href="#production-safety">Safety Layer</a> &bull;')
a('  <a href="#object-tracking">Tracking</a> &bull;')
a('  <a href="#benchmarks">Benchmarks</a> &bull;')
a('  <a href="#ros2-integration">ROS2</a> &bull;')
a('  <a href="#deployment-guide">Deployment</a>')
a('</p>')
a('')
a('---')
a('')
a('## What is TinyTPU')
a('')
a('TinyTPU is a complete edge AI inference stack designed for autonomous robots operating on resource-constrained hardware. It spans four layers:')
a('')
a('| Layer | What it does | Key metric |')
a('|-------|-------------|------------|')
a('| **Core Engine** | Systolic array matrix multiplication, activation functions, INT8 quantization | 199 GFLOPS peak, 75% memory reduction |')
a('| **ONNX Runtime** | Pure-Python ONNX inference with 50+ operators, automatic backend selection | Correlation 1.000 with ONNX Runtime |')
a('| **Edge AI Toolkit** | Hardware profiling, model zoo, auto-configuration, object detection pipeline | 3-line deployment, zero config |')
a('| **Production Layer** | Safety controller, Kalman tracking, async pipeline, black box recorder | 26 Hz control from 2 FPS vision |')
a('')
a('Most edge AI frameworks stop at inference. TinyTPU continues through perception, tracking, safety, and motor control. The result is a framework where a Raspberry Pi can autonomously follow a person with production-grade safety guarantees.')
a('')
a('---')
a('')
a('## Quick Start')
a('')
a('### Install')
a('')
a('```bash')
a('pip install numpy onnxruntime')
a('git clone https://github.com/SKBiswas1998/tinytpu.git')
a('cd tinytpu')
a('```')
a('')
a('### Detect objects (3 lines)')
a('')
a('```python')
a('from software.tinytpu.edge_ai import EdgeAI')
a('')
a('ai = EdgeAI.auto()  # Detects hardware, downloads best model, configures quantization')
a('result = ai.process(camera_frame)')
a('# result["detections"] -> [{class_name: "person", confidence: 0.92, ...}]')
a('# result["command"]    -> {action: "following", linear_x: 0.3, angular_z: -0.1}')
a('```')
a('')
a('### Production deployment (with safety)')
a('')
a('```python')
a('from software.tinytpu.edge_ai_v2 import ProductionEdgeAI')
a('')
a('ai = ProductionEdgeAI.auto(mode="follow", target="person")')
a('ai.start()  # Launches inference + control threads, thermal monitor, memory watchdog')
a('')
a('while running:')
a('    ai.push_frame(camera.read())       # Non-blocking, queues for inference')
a('    cmd = ai.get_command()              # 30 Hz Kalman-predicted safe command')
a('    robot.set_velocity(cmd.linear_x, cmd.angular_z)')
a('')
a('filepath = ai.stop()  # Saves black box log, returns path')
a('```')
a('')
a('### CLI tools')
a('')
a('```bash')
a('# Profile your hardware')
a('python -m software.tinytpu.edge_ai hardware')
a('')
a('# Benchmark inference speed')
a('python -m software.tinytpu.edge_ai benchmark')
a('')
a('# Live camera with robot control')
a('python -m software.tinytpu.edge_ai camera --mode follow --target person')
a('')
a('# Detect objects in an image')
a('python -m software.tinytpu.edge_ai detect --image photo.jpg')
a('```')
a('')
a('---')
a('')
a('## Architecture')
a('')
a('<p align="center">')
a('  <img src="docs/images/architecture.png" alt="Architecture" width="90%">')
a('</p>')
a('')
a('### Layer 1: Core Engine')
a('')
a('The foundation is a software systolic array that implements matrix multiplication the way hardware TPUs do, with data flowing through a grid of processing elements.')
a('')
a('<p align="center">')
a('  <img src="docs/images/systolic_array.png" alt="Systolic Array" width="70%">')
a('</p>')
a('')
a('Key capabilities:')
a('')
a('| Operation | Performance | Notes |')
a('|-----------|------------|-------|')
a('| Matrix multiply (1024x1024) | 199.2 GFLOPS | NumPy/PyTorch unified backend |')
a('| ReLU activation | 1.7x faster than PyTorch | Fused operations |')
a('| GELU activation | 1.3x faster than PyTorch | Exact computation |')
a('| LayerNorm | 1.1x faster than PyTorch | Single-pass algorithm |')
a('| INT8 quantization | 75% memory reduction | Per-tensor symmetric, r=0.9999 correlation |')
a('| GPT-2 124M inference | 11-15 tokens/sec | Full transformer stack |')
a('')
a('<p align="center">')
a('  <img src="docs/images/quantization.png" alt="Quantization" width="90%">')
a('</p>')
a('')
a('### Layer 2: ONNX Runtime')
a('')
a('A pure-Python ONNX inference engine that runs any ONNX model without external dependencies. It serves as a universal fallback when ONNX Runtime (C++) is unavailable, such as on some ARM boards where pre-built wheels do not exist.')
a('')
a('<p align="center">')
a('  <img src="docs/images/onnx_operators.png" alt="ONNX Operators" width="90%">')
a('</p>')
a('')
a('Supported operators include: Conv, MatMul, Gemm, BatchNormalization, LayerNormalization, Relu, Sigmoid, Tanh, Gelu, Softmax, Add, Mul, Div, Concat, Reshape, Transpose, Gather, Unsqueeze, Squeeze, Slice, Pad, Resize, MaxPool, AveragePool, GlobalAveragePool, ReduceMean, Sqrt, Pow, Erf, Cast, Clip, Where, Expand, Flatten, Shape, ConstantOfShape, Range, Tile, Split, and more.')
a('')
a('```python')
a('from software.tinytpu.onnx_engine import TinyTPUEngine')
a('')
a('engine = TinyTPUEngine("model.onnx")')
a('engine.summary()  # Parameters, operators, input/output shapes')
a('output, elapsed = engine.run({"input": data})')
a('stats = engine.benchmark({"input": data}, runs=10)')
a('```')
a('')
a('Backend selection is automatic:')
a('')
a('| Priority | Backend | Speed | Availability |')
a('|----------|---------|-------|-------------|')
a('| 1 | ONNX Runtime (C++) | Fastest (3-10x) | `pip install onnxruntime` |')
a('| 2 | TinyTPU Engine | Medium | Always available |')
a('| 3 | NumPy fallback | Slowest | Always available |')

print(f"Part 1: {len(lines)} lines")
with open('README.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print("README Part 1 written")
