lines = []
a = lines.append

a('')
a('---')
a('')
a('## Edge AI Toolkit')
a('')
a('The toolkit auto-configures everything based on your hardware. No manual tuning required.')
a('')
a('### Hardware Detection')
a('')
a('`detect_hardware()` profiles your device and recommends optimal settings:')
a('')
a('```python')
a('from software.tinytpu.edge_ai import detect_hardware, recommend_model')
a('')
a('hw = detect_hardware()')
a('print(hw)')
a('# Device: Raspberry Pi 5 Model B Rev 1.0')
a('# CPU: 4 cores @ 2400MHz (aarch64)')
a('# RAM: 4096MB total, 3200MB available')
a('# Max model size: 1120MB')
a('# Recommended: int8, 640px')
a('```')
a('')
a('Automatic configuration across devices:')
a('')
a('| Device | RAM | Quantization | Image Size | Detection Model | Expected FPS |')
a('|--------|-----|-------------|------------|----------------|-------------|')
a('| Pi Zero W | 512 MB | INT8 | 320px | YOLOv5-nano (3.6 MB) | ~0.3 |')
a('| Pi 3B | 1 GB | INT8 | 320px | YOLOv5-small (14.1 MB) | ~0.5 |')
a('| Pi 4 (2 GB) | 2 GB | INT8 | 480px | YOLOv5-small (14.1 MB) | ~0.8 |')
a('| Pi 4 (4 GB) | 4 GB | INT8 | 640px | YOLOv5-small (14.1 MB) | ~1.0 |')
a('| Pi 5 (4 GB) | 4 GB | INT8 | 640px | YOLOv5-small (14.1 MB) | ~2.0 |')
a('| Pi 5 (8 GB) | 8 GB | FP32 | 640px | YOLOv5-small (14.1 MB) | ~2.5 |')
a('| Jetson Nano | 4 GB | INT8 | 640px | YOLOv5-small (14.1 MB) | ~6.0 |')
a('| Desktop x86 | 16 GB | FP32 | 640px | YOLOv5-small (14.1 MB) | ~5.7 |')
a('')
a('The system will not load a model that exceeds available memory. On a 512 MB Pi Zero, it selects YOLOv5-nano (3.6 MB) instead of YOLOv5-small (14.1 MB). On an 8 GB Pi 5, it uses FP32 precision since there is sufficient memory.')
a('')
a('### Model Zoo')
a('')
a('Pre-configured models with download URLs, size constraints, and expected performance:')
a('')
a('| Model | Task | Size (FP32) | Size (INT8) | Input | Min RAM |')
a('|-------|------|------------|------------|-------|---------|')
a('| YOLOv5-nano | Detection | 3.6 MB | 0.9 MB | 640px | 256 MB |')
a('| YOLOv5-small | Detection | 14.1 MB | 3.5 MB | 640px | 512 MB |')
a('| MobileNetV2 | Classification | 13.3 MB | 3.4 MB | 224px | 128 MB |')
a('')
a('Models are downloaded automatically on first use from GitHub releases.')
a('')
a('### Object Detection')
a('')
a('```python')
a('from software.tinytpu.edge_ai import ObjectDetector')
a('')
a('# Auto: detects hardware, picks model, downloads it')
a('detector = ObjectDetector.auto()')
a('')
a('# Manual: bring your own ONNX model')
a('detector = ObjectDetector("yolov5n.onnx", conf_thresh=0.4, img_size=640)')
a('')
a('detections = detector.detect(image)')
a('for det in detections:')
a('    print(f"{det.class_name}: {det.confidence:.0%} at ({det.cx:.0f}, {det.cy:.0f})")')
a('    # person: 92% at (320, 240)')
a('```')
a('')
a('The detection pipeline handles preprocessing (resize, normalize, NCHW conversion), inference through the selected backend, YOLO output parsing, non-maximum suppression, and coordinate scaling back to the original image dimensions. All 80 COCO classes are supported.')
a('')
a('### Robot Control')
a('')
a('Three control modes convert detections directly into velocity commands:')
a('')
a('| Mode | Behavior | Use case |')
a('|------|----------|----------|')
a('| `follow` | Proportional steering toward target, speed based on apparent distance | Person following, object retrieval |')
a('| `avoid` | Drive forward, steer away from obstacles, emergency stop if too close | Autonomous navigation |')
a('| `patrol` | Sinusoidal wandering, report detected objects | Surveillance, mapping |')
a('')
a('```python')
a('from software.tinytpu.edge_ai import RobotController')
a('')
a('controller = RobotController(mode="follow", target_classes=["person"])')
a('cmd = controller.update(detections, image_width=640, image_height=480)')
a('print(f"v={cmd.linear_x:.2f} m/s, w={cmd.angular_z:.2f} rad/s")')
a('# v=0.15 m/s, w=-0.12 rad/s')
a('')
a('# ROS2 compatible output')
a('twist = cmd.to_twist_dict()')
a('# {"linear": {"x": 0.15, "y": 0, "z": 0}, "angular": {"x": 0, "y": 0, "z": -0.12}}')
a('```')
a('')
a('Follow mode uses proportional control: steering is proportional to the horizontal offset of the target from frame center, and speed scales with the apparent size of the target (larger = closer = slower). When no target is visible, the robot enters search mode, rotating in place and reversing direction periodically.')
a('')
a('<p align="center">')
a('  <img src="docs/images/pipeline.png" alt="Pipeline" width="90%">')
a('</p>')

print(f"Part 2: {len(lines)} lines")
with open('README.md', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print("README Part 2 appended")
