lines = []
a = lines.append

a('')
a('---')
a('')
a('## Production Safety')
a('')
a('The production layer (`edge_ai_v2.py`) addresses the gap between demo and deployment. Research shows that edge AI robots fail in the field from thermal throttling, memory exhaustion, and missing safety infrastructure, not from model quality. This layer solves those problems.')
a('')
a('### Safety Controller')
a('')
a('Every motor command passes through the safety controller before reaching the robot:')
a('')
a('```')
a('Perception -> Tracking -> Control -> [Safety Controller] -> Motors')
a('                                           |')
a('                                     E-stop check')
a('                                     Startup delay')
a('                                     Watchdog timeout')
a('                                     Proximity check')
a('                                     Velocity limits')
a('                                     Ramp rate limiting')
a('```')
a('')
a('```python')
a('from software.tinytpu.edge_ai_v2 import SafetyController')
a('')
a('safety = SafetyController(')
a('    max_linear=0.3,        # Hard limit: 0.3 m/s')
a('    max_angular=0.5,       # Hard limit: 0.5 rad/s')
a('    watchdog_timeout=2.0,  # Stop if no detection for 2s')
a('    ramp_rate=0.5,         # Max acceleration: 0.5 m/s/s')
a('    min_proximity=0.15,    # Stop if object fills >15% of frame')
a('    startup_delay=1.0,     # Wait 1s before allowing movement')
a(')')
a('')
a('# Every control cycle:')
a('safe_cmd = safety.filter_command(raw_cmd, detections, img_w, img_h)')
a('')
a('# Emergency stop (immediate, requires manual reset):')
a('safety.estop("obstacle_detected")')
a('safety.reset()  # Must be called explicitly to resume')
a('```')
a('')
a('Safety guarantees:')
a('')
a('| Feature | Behavior | Why it matters |')
a('|---------|----------|---------------|')
a('| E-stop | Immediate zero velocity, requires `reset()` | Prevents runaway robot |')
a('| Watchdog | Stops if vision pipeline hangs or crashes | Handles silent YOLO failures at ~20 min |')
a('| Velocity ramping | Max 0.5 m/s/s acceleration, 2x braking | No sudden movements |')
a('| Proximity stop | Zero forward velocity when object fills >15% of frame | Collision prevention |')
a('| Startup delay | 1 second hold before first movement | Prevents launch-time surge |')
a('| Hard limits | Clamps all velocities to configured max | Hardware protection |')
a('| Thread safety | All state changes are lock-protected | Safe for async pipeline |')
a('')
a('### Thermal Monitor')
a('')
a('CPU thermal throttling is the primary cause of performance degradation on Raspberry Pi. The OS reduces clock speed from 1.5 GHz to 1.0 GHz at 80C, causing a 40% inference speed drop with no warning. The thermal monitor detects this before it happens.')
a('')
a('```python')
a('from software.tinytpu.edge_ai_v2 import ThermalMonitor')
a('')
a('thermal = ThermalMonitor(warn_temp=70, critical_temp=78, shutdown_temp=85)')
a('thermal.start()  # Background thread polls every 2s')
a('')
a('# Auto-throttle inference rate based on temperature:')
a('skip = thermal.get_skip_factor()')
a('# 0 = full speed, 1 = every other frame, 2 = every 3rd, 4 = minimal')
a('```')
a('')
a('| Temperature | Throttle Level | Skip Factor | Effective FPS (from 3 FPS) |')
a('|-------------|---------------|-------------|---------------------------|')
a('| < 70C | None | 0 | 3.0 |')
a('| 70-78C | Warn | 1 | 1.5 |')
a('| 78-85C | Critical | 2 | 1.0 |')
a('| > 85C | Shutdown | 4 | 0.6 |')
a('')
a('Cross-platform temperature reading: Linux thermal zones, `vcgencmd` on Raspberry Pi, WMI on Windows.')
a('')
a('### Memory Watchdog')
a('')
a('YOLO on a 2 GB Raspberry Pi silently crashes after approximately 20 minutes. The OOM killer terminates the process without any log entry. The memory watchdog prevents this.')
a('')
a('```python')
a('from software.tinytpu.edge_ai_v2 import MemoryWatchdog')
a('')
a('memory = MemoryWatchdog(')
a('    warn_percent=70,       # System RAM usage warning')
a('    critical_percent=85,   # Trigger GC + callback')
a('    max_rss_mb=0,          # Auto: 50% of total RAM')
a('    on_critical=lambda: safety.estop("OOM_imminent"),  # E-stop before crash')
a(')')
a('memory.start()  # Background thread polls every 5s')
a('```')
a('')
a('When memory reaches the critical threshold, the watchdog forces garbage collection and triggers the configured callback. In the default `ProductionEdgeAI` configuration, this fires an E-stop, ensuring the robot stops safely instead of crashing at full speed.')

print(f"Part 3: {len(lines)} lines")
with open('README.md', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print("README Part 3 appended")
