lines = []
a = lines.append

a('')
a('---')
a('')
a('## Object Tracking')
a('')
a('At 2 FPS inference, a robot is blind 93% of the time. The tracking layer fills the gaps with Kalman prediction, enabling 30 Hz control from slow vision.')
a('')
a('### Kalman Filter')
a('')
a('Each tracked object carries an 8-state Kalman filter: `[cx, cy, w, h, vx, vy, vw, vh]`. Between detection frames, the filter predicts where the object has moved based on estimated velocity.')
a('')
a('```python')
a('from software.tinytpu.edge_ai_v2 import KalmanFilter2D')
a('')
a('kf = KalmanFilter2D(initial_bbox=(320, 240, 100, 200))')
a('')
a('# At detection time (~2 FPS):')
a('kf.update((325, 238, 102, 198))  # Correct with measurement')
a('')
a('# Between detections (~30 Hz):')
a('predicted_bbox = kf.predict()     # Extrapolate from velocity')
a('vx, vy = kf.velocity              # Pixels/sec')
a('```')
a('')
a('Measured accuracy on constant-velocity targets:')
a('')
a('| Metric | Value | Context |')
a('|--------|-------|---------|')
a('| Mean position error | 24.1 px | On 640px frame (3.8% error) |')
a('| Max position error | 49.5 px | Worst-case between detections |')
a('| Median error | 23.1 px | Stable tracking |')
a('| Error at detection | ~0 px | Corrected by measurement update |')
a('| Convergence | < 3 frames | Velocity estimate stabilizes quickly |')
a('')
a('### IoU Tracker')
a('')
a('The `ObjectTracker` implements SORT (Simple Online Realtime Tracking): detection-to-track matching via IoU, automatic track creation and deletion, and persistent object IDs across frames.')
a('')
a('```python')
a('from software.tinytpu.edge_ai_v2 import ObjectTracker')
a('')
a('tracker = ObjectTracker(')
a('    iou_threshold=0.3,   # Min overlap to match detection to track')
a('    max_missed=15,       # Frames before removing lost track')
a('    min_hits=2,          # Detections before confirming track')
a('    max_tracks=50,       # Memory protection')
a(')')
a('')
a('# At detection time:')
a('tracks = tracker.update(detections)  # Match, update Kalman, return confirmed')
a('')
a('# Between detections:')
a('tracks = tracker.predict()           # Kalman-only, no matching needed')
a('')
a('# Get detections from tracks (for controller):')
a('predicted_dets = tracker.get_detections(tracks)')
a('')
a('# Access individual tracks:')
a('for t in tracks:')
a('    print(f"ID {t.track_id}: {t.class_name}, seen {t.frames_seen}x, conf {t.confidence:.0%}")')
a('```')
a('')
a('Track lifecycle:')
a('')
a('```')
a('Detection appears -> Tentative track (ID assigned, Kalman initialized)')
a('    -> min_hits reached -> Confirmed track (visible to controller)')
a('    -> detection missed -> frames_missed increments, confidence decays')
a('    -> max_missed exceeded -> Track deleted')
a('```')
a('')
a('### Async Pipeline')
a('')
a('The async pipeline decouples camera capture, neural network inference, and robot control into separate threads:')
a('')
a('```')
a('+------------------+     +------------------+     +------------------+')
a('| Camera Thread    | --> | Inference Thread  | --> | Control Thread   |')
a('| (camera rate)    |     | (2-8 FPS)         |     | (30 Hz)          |')
a('+------------------+     +------------------+     +------------------+')
a('  Grabs latest frame      Processes when ready      Kalman predict')
a('  Non-blocking             Updates tracker           Safety filter')
a('  Drops old frames         Feeds watchdog            Motor commands')
a('```')
a('')
a('```python')
a('from software.tinytpu.edge_ai_v2 import AsyncPipeline')
a('')
a('pipeline = AsyncPipeline(detector, controller, tracker, safety, thermal, target_hz=30)')
a('pipeline.start()')
a('')
a('# Main loop (non-blocking):')
a('pipeline.push_frame(frame)       # Returns immediately')
a('cmd = pipeline.get_command()      # Latest safe command at 30 Hz')
a('dets = pipeline.get_detections()  # Latest tracked detections')
a('')
a('status = pipeline.get_status()')
a('# {"inference_fps": 7.8, "control_fps": 26.2, "frames_captured": 59, ...}')
a('```')
a('')
a('Measured performance on desktop (ONNX Runtime backend):')
a('')
a('| Metric | Value |')
a('|--------|-------|')
a('| Inference FPS | 7.8 |')
a('| Control FPS | 26.2 |')
a('| Frames captured (3s test) | 59 |')
a('| Frames inferred | 22 |')
a('| Frames skipped (thermal) | 0 |')

print(f"Part 4: {len(lines)} lines")
with open('README.md', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print("README Part 4 appended")
