lines = []
a = lines.append

a('')
a('---')
a('')
a('## Field Debugging')
a('')
a('### Black Box Recorder')
a('')
a('Flight-recorder style logging that captures everything needed to diagnose field failures offline. All events are timestamped with monotonic and wall clocks for correlation with external logs.')
a('')
a('```python')
a('from software.tinytpu.edge_ai_v2 import BlackBoxRecorder')
a('')
a('recorder = BlackBoxRecorder(')
a('    log_dir="blackbox",          # Output directory')
a('    max_entries=10000,           # Circular buffer (overwrites oldest)')
a('    save_frames_on_event=True,   # Save numpy frames on E-stop, timeout, etc.')
a('    max_frame_snapshots=100,')
a(')')
a('')
a('# Automatic recording in ProductionEdgeAI, or manual:')
a('recorder.record_detection(detections, inference_ms=150.0)')
a('recorder.record_command(cmd)')
a('recorder.record_safety_event("estop", "obstacle at 0.3m", frame=current_frame)')
a('recorder.record_metrics({"temp": 72.5, "rss_mb": 180.3, "fps": 2.1})')
a('')
a('# Save and analyze:')
a('filepath = recorder.save()  # blackbox/blackbox_20240115_143022.json')
a('log = BlackBoxRecorder.load(filepath)')
a('```')
a('')
a('Log format (JSON):')
a('')
a('```json')
a('{')
a('  "session_id": "20240115_143022",')
a('  "duration_s": 3847.2,')
a('  "total_entries": 48291,')
a('  "entries": [')
a('    {"t": 0.033, "wall": 1705312222.5, "seq": 0, "type": "detection",')
a('     "data": {"count": 2, "objects": [{"class": "person", "conf": 0.92}], "inference_ms": 156.3}},')
a('    {"t": 0.034, "wall": 1705312222.5, "seq": 1, "type": "command",')
a('     "data": {"linear_x": 0.15, "angular_z": -0.08, "action": "following"}}')
a('  ]')
a('}')
a('```')
a('')
a('### Image Quality Scorer')
a('')
a('Detects degraded camera input before it causes bad decisions. All computation uses NumPy only, no OpenCV dependency.')
a('')
a('```python')
a('from software.tinytpu.edge_ai_v2 import ImageQualityScorer')
a('')
a('quality = ImageQualityScorer()')
a('result = quality.score(frame)')
a('# {"score": 82.3, "blur": 245.6, "brightness": 124.0, "contrast": 45.2,')
a('#  "issues": [], "usable": True}')
a('')
a('# Trend monitoring:')
a('trend = quality.get_trend()')
a('# {"avg_score": 78.1, "min_score": 42.0, "degrading": False, "samples": 100,')
a('#  "issue_counts": {"blurry": 3, "dark": 12, "overexposed": 0, ...}}')
a('```')
a('')
a('| Check | Method | Threshold | Detects |')
a('|-------|--------|-----------|---------|')
a('| Blur | Laplacian variance | < 50.0 | Lens smudge, motion blur, defocus |')
a('| Darkness | Mean pixel intensity | < 40.0 | Night, covered lens, shadows |')
a('| Overexposure | Mean pixel intensity | > 220.0 | Direct sunlight, glare |')
a('| Low contrast | Pixel standard deviation | < 30.0 | Fog, mist, featureless walls |')
a('| Occlusion | Peak-to-peak range | < 15.0 | Lens covered, uniform obstruction |')
a('')
a('In the default `ProductionEdgeAI` configuration, unusable frames trigger a black box event and frame snapshot for later analysis.')
a('')
a('---')
a('')
a('## Benchmarks')
a('')
a('### Core Engine')
a('')
a('Benchmarked against PyTorch on identical workloads:')
a('')
a('| Operation | TinyTPU | PyTorch | Speedup |')
a('|-----------|---------|---------|---------|')
a('| MatMul 1024x1024 | 4.2 ms | 3.3 ms | 0.8x |')
a('| ReLU 10M elements | 2.1 ms | 3.5 ms | 1.7x |')
a('| GELU 10M elements | 4.8 ms | 6.4 ms | 1.3x |')
a('| LayerNorm 10M elements | 12.4 ms | 13.6 ms | 1.1x |')
a('| Softmax 10M elements | 6.2 ms | 5.0 ms | 0.8x |')
a('| GPT-2 inference | 11-15 tok/s | 20-25 tok/s | ~0.6x |')
a('')
a('### INT8 Quantization')
a('')
a('| Metric | Value |')
a('|--------|-------|')
a('| Memory reduction | 75% (FP32 to INT8) |')
a('| Accuracy correlation | r = 0.9999 |')
a('| Max absolute error | < 0.01 |')
a('| Quantization time | < 100 ms for GPT-2 |')
a('')
a('### Detection Pipeline')
a('')
a('| Device | Backend | Model | FPS | Latency |')
a('|--------|---------|-------|-----|---------|')
a('| Desktop (i7) | ONNX Runtime | YOLOv5s | 5.7 | 175 ms |')
a('| Desktop (i7) | TinyTPU Engine | YOLOv5s | ~1.5 | ~670 ms |')
a('| Raspberry Pi 5 | ONNX Runtime | YOLOv5s | ~2-3 | ~400 ms |')
a('| Raspberry Pi 4 | ONNX Runtime | YOLOv5s | ~0.8 | ~1200 ms |')
a('| Raspberry Pi 5 | ONNX Runtime | YOLOv5n | ~5-7 | ~170 ms |')
a('| Jetson Nano | ONNX Runtime | YOLOv5s | ~6 | ~170 ms |')
a('')
a('### Validated Detection Results')
a('')
a('Tested on COCO bus.jpg (810x1080):')
a('')
a('| Object | Confidence | Bounding Box |')
a('|--------|-----------|-------------|')
a('| Person 1 | 90% | (53, 390) - (244, 911) |')
a('| Person 2 | 88% | (672, 387) - (809, 877) |')
a('| Person 3 | 80% | (223, 410) - (344, 857) |')
a('| Bus | 66% | (-5, 221) - (801, 773) |')
a('| Person 4 | 56% | (-0, 549) - (73, 873) |')

print(f"Part 5: {len(lines)} lines")
with open('README.md', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print("README Part 5 appended")
