lines = []
a = lines.append

a('')
a('---')
a('')
a('## ROS2 Integration')
a('')
a('TinyTPU provides three ROS2 nodes for direct integration with robotics stacks:')
a('')
a('```')
a('+------------+     +------------+     +------------+')
a('| vision_node| --> | brain_node | --> | cmd_vel    |')
a('| (camera +  |     | (NL commands|     | (Twist)    |')
a('|  detection)|     |  + planning)|     |            |')
a('+------------+     +------------+     +------------+')
a('       |                                    ^')
a('       v                                    |')
a('+------------+                        +------------+')
a('| llm_node   |                        | safety     |')
a('| (natural   | ---------------------->| controller |')
a('|  language)  |                        +------------+')
a('+------------+')
a('```')
a('')
a('### vision_node')
a('')
a('Subscribes to camera images, runs YOLO detection, publishes annotated results.')
a('')
a('```bash')
a('ros2 run tinytpu vision_node --ros-args \\')
a('  -p model:=yolov5s.onnx \\')
a('  -p confidence:=0.4 \\')
a('  -p camera_topic:=/camera/image_raw')
a('```')
a('')
a('Publishes: `/tinytpu/detections` (Detection array), `/tinytpu/annotated_image` (annotated camera view)')
a('')
a('### brain_node')
a('')
a('Natural language command interface for robot control:')
a('')
a('```python')
a('# Natural language -> robot behavior')
a('"follow the person" -> mode="follow", target="person"')
a('"avoid obstacles"   -> mode="avoid"')
a('"patrol the area"   -> mode="patrol"')
a('"stop"              -> e-stop')
a('```')
a('')
a('### llm_node')
a('')
a('On-device LLM reasoning for complex decision-making. Uses the TinyTPU GPT-2 inference engine for natural language understanding and planning.')
a('')
a('---')
a('')
a('## Deployment Guide')
a('')
a('### Raspberry Pi Setup')
a('')
a('```bash')
a('# 1. Install system dependencies')
a('sudo apt update && sudo apt install -y python3-pip libatlas-base-dev')
a('')
a('# 2. Install Python packages')
a('pip3 install numpy onnxruntime')
a('')
a('# 3. Clone and test')
a('git clone https://github.com/SKBiswas1998/tinytpu.git')
a('cd tinytpu')
a('python3 -c "from software.tinytpu.edge_ai import EdgeAI; print(EdgeAI.auto())"')
a('```')
a('')
a('### Thermal Management')
a('')
a('Active cooling is essential for sustained inference. A Pi 5 reaches 80C in approximately 50 seconds under YOLO inference load, triggering a 40% clock reduction.')
a('')
a('| Cooling Method | Max Sustained Temp | Throughput Retention |')
a('|---------------|-------------------|---------------------|')
a('| No cooling | 85C (throttled) | 60% |')
a('| Passive heatsink | 75C | 80% |')
a('| Active fan (5V) | 55C | 100% |')
a('| ICE Tower cooler | 45C | 100% |')
a('')
a('Recommendation: always use active cooling for production deployments. The ThermalMonitor handles graceful degradation when cooling is insufficient.')
a('')
a('### Memory Planning')
a('')
a('| Device RAM | Available After OS | Max Model Size | Recommended Config |')
a('|-----------|-------------------|---------------|-------------------|')
a('| 512 MB | ~350 MB | ~120 MB | INT8, 320px, YOLOv5n |')
a('| 1 GB | ~700 MB | ~250 MB | INT8, 320px, YOLOv5s |')
a('| 2 GB | ~1500 MB | ~500 MB | INT8, 480px, YOLOv5s |')
a('| 4 GB | ~3200 MB | ~1100 MB | INT8, 640px, YOLOv5s |')
a('| 8 GB | ~6800 MB | ~2400 MB | FP32, 640px, YOLOv5s |')
a('')
a('The MemoryWatchdog auto-configures the RSS limit to 50% of total RAM, leaving headroom for the OS, camera driver, and ROS2 nodes.')
a('')
a('### Low FPS Strategies')
a('')
a('At 2-3 FPS, additional techniques become essential:')
a('')
a('| Strategy | Implementation | Benefit |')
a('|----------|---------------|---------|')
a('| Kalman prediction | `ObjectTracker.predict()` at 30 Hz | Smooth control between frames |')
a('| Async pipeline | Separate capture/inference/control threads | Camera never blocks on inference |')
a('| Thermal throttling | `ThermalMonitor.get_skip_factor()` | Prevent OS clock reduction |')
a('| Frame skipping | Process newest frame, drop queue | Always work with latest data |')
a('| Small models | YOLOv5n instead of YOLOv5s | 2-3x faster, slight accuracy loss |')
a('')
a('### Dependency Matrix')
a('')
a('| Package | Required | Purpose | Size |')
a('|---------|----------|---------|------|')
a('| numpy | Yes | Core computation | 15 MB |')
a('| onnxruntime | Recommended | Fast inference (3-10x) | 25 MB |')
a('| pillow | Optional | Image loading (test suite) | 3 MB |')
a('| opencv-python | Optional | Camera capture, visualization | 50 MB |')
a('| rclpy | Optional | ROS2 node integration | System |')
a('')
a('---')
a('')
a('## Testing')
a('')
a('The project includes two comprehensive test suites:')
a('')
a('```bash')
a('# Core toolkit tests (78 tests)')
a('python test_capabilities.py')
a('#   Hardware simulation (9 devices)')
a('#   Detection pipeline (all resolutions)')
a('#   NMS stress test (5000 boxes)')
a('#   Robot controller edge cases (12 scenarios)')
a('#   Follow person simulation (50 frames)')
a('#   Memory profiling (leak detection)')
a('#   Latency breakdown (preprocess/inference/postprocess)')
a('#   Full pipeline stress (100 frames)')
a('')
a('# Production layer tests (83 tests)')
a('python test_v2.py')
a('#   Safety controller (e-stop, watchdog, ramping, proximity, limits)')
a('#   Thermal monitor (temperature reading, skip factor)')
a('#   Memory watchdog (RSS tracking, system memory)')
a('#   Kalman filter (prediction, update, velocity estimation)')
a('#   Object tracker (IoU matching, persistent IDs, track lifecycle)')
a('#   Async pipeline (threaded inference, control rate)')
a('#   Black box recorder (circular buffer, save/load, filtering)')
a('#   Image quality (blur, dark, overexposed, occluded, empty)')
a('#   Production integration (sync mode, e-stop, full status)')
a('#   Kalman accuracy (30 Hz from 2 FPS, position error measurement)')
a('#   Real image detection (COCO bus.jpg, person + bus detection)')
a('```')
a('')
a('Current results: **161 tests, 159 passing (99%)**. Two known non-critical failures: quality scorer sample count edge case and Kalman convergence timing (error already below threshold).')

print(f"Part 6: {len(lines)} lines")
with open('README.md', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print("README Part 6 appended")
