lines = []
a = lines.append

a('')
a('')
a('# ================================================================')
a('# TIER 2: TRACKING & ASYNC PIPELINE')
a('# ================================================================')
a('')
a('')
a('class KalmanFilter2D:')
a('    """')
a('    2D Kalman filter for bounding box tracking.')
a('')
a('    State: [cx, cy, w, h, vx, vy, vw, vh]')
a('    Measurement: [cx, cy, w, h]')
a('')
a('    Predicts object position between slow inference frames,')
a('    enabling 30Hz control from 2 FPS vision.')
a('    """')
a('')
a('    def __init__(self, initial_bbox: Tuple[float, float, float, float],')
a('                 process_noise: float = 1.0,')
a('                 measurement_noise: float = 1.0):')
a('        """')
a('        Args:')
a('            initial_bbox: (cx, cy, w, h)')
a('            process_noise: Higher = trust predictions less')
a('            measurement_noise: Higher = trust measurements less')
a('        """')
a('        cx, cy, w, h = initial_bbox')
a('')
a('        # State [cx, cy, w, h, vx, vy, vw, vh]')
a('        self.x = np.array([cx, cy, w, h, 0, 0, 0, 0], dtype=np.float64)')
a('')
a('        # State transition (constant velocity)')
a('        self.F = np.eye(8, dtype=np.float64)')
a('        # dt gets set in predict()')
a('')
a('        # Measurement matrix (observe position + size)')
a('        self.H = np.zeros((4, 8), dtype=np.float64)')
a('        self.H[0, 0] = 1  # cx')
a('        self.H[1, 1] = 1  # cy')
a('        self.H[2, 2] = 1  # w')
a('        self.H[3, 3] = 1  # h')
a('')
a('        # Covariance')
a('        self.P = np.eye(8, dtype=np.float64) * 10.0')
a('        self.P[4:, 4:] *= 100.0  # high uncertainty on initial velocity')
a('')
a('        # Process noise')
a('        self.Q_base = np.eye(8, dtype=np.float64) * process_noise')
a('        self.Q_base[4:, 4:] *= 4.0  # velocity changes more')
a('')
a('        # Measurement noise')
a('        self.R = np.eye(4, dtype=np.float64) * measurement_noise')
a('')
a('        self.last_time = time.monotonic()')
a('        self.age = 0')
a('')
a('    def predict(self, dt: float = None) -> Tuple[float, float, float, float]:')
a('        """Predict next state. Returns (cx, cy, w, h)."""')
a('        now = time.monotonic()')
a('        if dt is None:')
a('            dt = now - self.last_time')
a('        self.last_time = now')
a('        dt = max(dt, 0.001)')
a('')
a('        # Update transition matrix with dt')
a('        self.F = np.eye(8, dtype=np.float64)')
a('        self.F[0, 4] = dt  # cx += vx * dt')
a('        self.F[1, 5] = dt  # cy += vy * dt')
a('        self.F[2, 6] = dt  # w += vw * dt')
a('        self.F[3, 7] = dt  # h += vh * dt')
a('')
a('        # Scale process noise by dt')
a('        Q = self.Q_base * dt')
a('')
a('        # Predict')
a('        self.x = self.F @ self.x')
a('        self.P = self.F @ self.P @ self.F.T + Q')
a('')
a('        # Clamp size to positive')
a('        self.x[2] = max(self.x[2], 1.0)')
a('        self.x[3] = max(self.x[3], 1.0)')
a('')
a('        self.age += 1')
a('        return tuple(self.x[:4])')
a('')
a('    def update(self, measurement: Tuple[float, float, float, float]):')
a('        """Update with actual measurement (cx, cy, w, h)."""')
a('        z = np.array(measurement, dtype=np.float64)')
a('')
a('        # Innovation')
a('        y = z - self.H @ self.x')
a('        S = self.H @ self.P @ self.H.T + self.R')
a('')
a('        # Kalman gain')
a('        try:')
a('            K = self.P @ self.H.T @ np.linalg.inv(S)')
a('        except np.linalg.LinAlgError:')
a('            return  # skip update if singular')
a('')
a('        # Update')
a('        self.x = self.x + K @ y')
a('        I = np.eye(8, dtype=np.float64)')
a('        self.P = (I - K @ self.H) @ self.P')
a('')
a('        # Clamp size')
a('        self.x[2] = max(self.x[2], 1.0)')
a('        self.x[3] = max(self.x[3], 1.0)')
a('        self.age = 0')
a('')
a('    @property')
a('    def velocity(self) -> Tuple[float, float]:')
a('        """Return (vx, vy) in pixels/sec."""')
a('        return (self.x[4], self.x[5])')
a('')
a('    @property')
a('    def bbox(self) -> Tuple[float, float, float, float]:')
a('        """Return current (cx, cy, w, h)."""')
a('        return tuple(self.x[:4])')
a('')
a('')
a('@dataclass')
a('class TrackedObject:')
a('    """A persistently tracked object with ID and history."""')
a('    track_id: int')
a('    class_id: int')
a('    class_name: str')
a('    kalman: KalmanFilter2D')
a('    confidence: float = 0.0')
a('    frames_seen: int = 1')
a('    frames_missed: int = 0')
a('    last_detection: Optional[Detection] = None')
a('    history: list = field(default_factory=list)  # last N positions')
a('')
a('    def to_detection(self) -> Detection:')
a('        """Convert current Kalman state to Detection."""')
a('        cx, cy, w, h = self.kalman.bbox')
a('        x1 = cx - w / 2')
a('        y1 = cy - h / 2')
a('        x2 = cx + w / 2')
a('        y2 = cy + h / 2')
a('        return Detection(self.class_id, self.class_name, self.confidence, x1, y1, x2, y2)')
a('')
a('')
a('class ObjectTracker:')
a('    """')
a('    IoU-based multi-object tracker with Kalman prediction.')
a('')
a('    - Assigns persistent IDs to objects across frames')
a('    - Predicts positions between inference frames')
a('    - Handles object enter/exit/occlusion')
a('    - Provides 30Hz tracking from 2 FPS detection')
a('')
a('    Based on SORT algorithm (Simple Online Realtime Tracking).')
a('    """')
a('')
a('    def __init__(self,')
a('                 iou_threshold: float = 0.3,')
a('                 max_missed: int = 15,')
a('                 min_hits: int = 2,')
a('                 max_tracks: int = 50):')
a('        """')
a('        Args:')
a('            iou_threshold: Min IoU to match detection to track')
a('            max_missed: Frames without match before track is removed')
a('            min_hits: Detections needed before track is confirmed')
a('            max_tracks: Maximum simultaneous tracks')
a('        """')
a('        self.iou_threshold = iou_threshold')
a('        self.max_missed = max_missed')
a('        self.min_hits = min_hits')
a('        self.max_tracks = max_tracks')
a('')
a('        self.tracks: Dict[int, TrackedObject] = {}')
a('        self.next_id = 1')
a('        self.frame_count = 0')
a('')
a('    @staticmethod')
a('    def _iou(box1, box2) -> float:')
a('        """Compute IoU between two (cx,cy,w,h) boxes."""')
a('        # Convert to x1y1x2y2')
a('        ax1 = box1[0] - box1[2] / 2')
a('        ay1 = box1[1] - box1[3] / 2')
a('        ax2 = box1[0] + box1[2] / 2')
a('        ay2 = box1[1] + box1[3] / 2')
a('')
a('        bx1 = box2[0] - box2[2] / 2')
a('        by1 = box2[1] - box2[3] / 2')
a('        bx2 = box2[0] + box2[2] / 2')
a('        by2 = box2[1] + box2[3] / 2')
a('')
a('        ix1 = max(ax1, bx1)')
a('        iy1 = max(ay1, by1)')
a('        ix2 = min(ax2, bx2)')
a('        iy2 = min(ay2, by2)')
a('')
a('        if ix2 <= ix1 or iy2 <= iy1:')
a('            return 0.0')
a('')
a('        inter = (ix2 - ix1) * (iy2 - iy1)')
a('        area1 = (ax2 - ax1) * (ay2 - ay1)')
a('        area2 = (bx2 - bx1) * (by2 - by1)')
a('        union = area1 + area2 - inter')
a('')
a('        return inter / union if union > 0 else 0.0')
a('')
a('    def update(self, detections: List[Detection]) -> List[TrackedObject]:')
a('        """')
a('        Update tracks with new detections.')
a('')
a('        Returns list of confirmed tracked objects.')
a('        """')
a('        self.frame_count += 1')
a('')
a('        # 1. Predict all existing tracks')
a('        for track in self.tracks.values():')
a('            track.kalman.predict()')
a('')
a('        # 2. Build cost matrix (negative IoU)')
a('        track_ids = list(self.tracks.keys())')
a('        if len(track_ids) > 0 and len(detections) > 0:')
a('            cost = np.zeros((len(track_ids), len(detections)))')
a('            for i, tid in enumerate(track_ids):')
a('                track_bbox = self.tracks[tid].kalman.bbox')
a('                for j, det in enumerate(detections):')
a('                    det_bbox = (det.cx, det.cy, det.width, det.height)')
a('                    cost[i, j] = -self._iou(track_bbox, det_bbox)')
a('')
a('            # 3. Greedy matching (simple but fast)')
a('            matched_tracks = set()')
a('            matched_dets = set()')
a('')
a('            while True:')
a('                if cost.size == 0:')
a('                    break')
a('                min_idx = np.unravel_index(np.argmin(cost), cost.shape)')
a('                min_val = cost[min_idx]')
a('                if -min_val < self.iou_threshold:')
a('                    break')
a('')
a('                ti, di = min_idx')
a('                tid = track_ids[ti]')
a('                det = detections[di]')
a('')
a('                # Update matched track')
a('                track = self.tracks[tid]')
a('                track.kalman.update((det.cx, det.cy, det.width, det.height))')
a('                track.confidence = det.confidence')
a('                track.frames_seen += 1')
a('                track.frames_missed = 0')
a('                track.last_detection = det')
a('                if len(track.history) > 100:')
a('                    track.history.pop(0)')
a('                track.history.append((det.cx, det.cy))')
a('')
a('                matched_tracks.add(ti)')
a('                matched_dets.add(di)')
a('')
a('                # Block this row/col')
a('                cost[ti, :] = 0')
a('                cost[:, di] = 0')
a('')
a('            # 4. Unmatched tracks: increment missed')
a('            for i, tid in enumerate(track_ids):')
a('                if i not in matched_tracks:')
a('                    self.tracks[tid].frames_missed += 1')
a('                    self.tracks[tid].confidence *= 0.9  # decay')
a('')
a('            # 5. Unmatched detections: create new tracks')
a('            for j, det in enumerate(detections):')
a('                if j not in matched_dets and len(self.tracks) < self.max_tracks:')
a('                    self._create_track(det)')
a('')
a('        elif len(detections) > 0:')
a('            # No existing tracks, create all')
a('            for det in detections[:self.max_tracks]:')
a('                self._create_track(det)')
a('')
a('        else:')
a('            # No detections, all tracks miss')
a('            for track in self.tracks.values():')
a('                track.frames_missed += 1')
a('                track.confidence *= 0.9')
a('')
a('        # 6. Remove dead tracks')
a('        dead = [tid for tid, t in self.tracks.items() if t.frames_missed > self.max_missed]')
a('        for tid in dead:')
a('            del self.tracks[tid]')
a('')
a('        # 7. Return confirmed tracks')
a('        confirmed = [t for t in self.tracks.values() if t.frames_seen >= self.min_hits]')
a('        return sorted(confirmed, key=lambda t: t.confidence, reverse=True)')
a('')
a('    def predict(self) -> List[TrackedObject]:')
a('        """')
a('        Predict all track positions WITHOUT new detections.')
a('        Call this between inference frames for 30Hz tracking.')
a('        """')
a('        for track in self.tracks.values():')
a('            track.kalman.predict()')
a('        confirmed = [t for t in self.tracks.values() if t.frames_seen >= self.min_hits]')
a('        return sorted(confirmed, key=lambda t: t.confidence, reverse=True)')
a('')
a('    def get_detections(self, tracks: List[TrackedObject] = None) -> List[Detection]:')
a('        """Convert current tracked objects to Detection list."""')
a('        if tracks is None:')
a('            tracks = [t for t in self.tracks.values() if t.frames_seen >= self.min_hits]')
a('        return [t.to_detection() for t in tracks]')
a('')
a('    def _create_track(self, det: Detection):')
a('        bbox = (det.cx, det.cy, det.width, det.height)')
a('        kf = KalmanFilter2D(bbox)')
a('        track = TrackedObject(')
a('            track_id=self.next_id,')
a('            class_id=det.class_id,')
a('            class_name=det.class_name,')
a('            kalman=kf,')
a('            confidence=det.confidence,')
a('            last_detection=det,')
a('            history=[(det.cx, det.cy)]')
a('        )')
a('        self.tracks[self.next_id] = track')
a('        self.next_id += 1')
a('')
a('    def get_track(self, track_id: int) -> Optional[TrackedObject]:')
a('        return self.tracks.get(track_id)')
a('')
a('    def get_status(self) -> dict:')
a('        return {')
a('            "active_tracks": len(self.tracks),')
a('            "confirmed_tracks": sum(1 for t in self.tracks.values() if t.frames_seen >= self.min_hits),')
a('            "next_id": self.next_id,')
a('            "frame_count": self.frame_count,')
a('        }')
a('')
a('')
a('class AsyncPipeline:')
a('    """')
a('    Threaded capture -> inference -> control pipeline.')
a('')
a('    Problem: At 1-3 FPS inference, if capture blocks on inference,')
a('    you get 1-3 Hz control. Robot is blind between frames.')
a('')
a('    Solution: Three threads:')
a('      1. Capture thread: grabs frames as fast as camera allows')
a('      2. Inference thread: processes latest frame when ready')
a('      3. Control runs at fixed rate using Kalman predictions')
a('')
a('    Control loop runs at target_hz (default 30) even when')
a('    inference runs at 2 FPS.')
a('    """')
a('')
a('    def __init__(self,')
a('                 detector: ObjectDetector,')
a('                 controller: RobotController,')
a('                 tracker: ObjectTracker = None,')
a('                 safety: SafetyController = None,')
a('                 thermal: ThermalMonitor = None,')
a('                 target_hz: float = 30.0):')
a('        self.detector = detector')
a('        self.controller = controller')
a('        self.tracker = tracker or ObjectTracker()')
a('        self.safety = safety or SafetyController()')
a('        self.thermal = thermal')
a('        self.target_hz = target_hz')
a('')
a('        # Shared state (protected by locks)')
a('        self._frame_lock = threading.Lock()')
a('        self._result_lock = threading.Lock()')
a('        self._latest_frame = None')
a('        self._frame_id = 0')
a('        self._last_processed_id = -1')
a('        self._latest_detections: List[Detection] = []')
a('        self._latest_command = RobotCommand(0, 0, 0, "startup", "Initializing")')
a('        self._img_w = 640')
a('        self._img_h = 480')
a('')
a('        # Stats')
a('        self.inference_fps = 0.0')
a('        self.control_fps = 0.0')
a('        self.capture_fps = 0.0')
a('        self.frames_captured = 0')
a('        self.frames_inferred = 0')
a('        self.frames_skipped = 0')
a('')
a('        self._running = False')
a('        self._threads = []')
a('')
a('    def push_frame(self, frame: np.ndarray):')
a('        """Push a new camera frame. Non-blocking."""')
a('        with self._frame_lock:')
a('            self._latest_frame = frame')
a('            self._frame_id += 1')
a('            self._img_h, self._img_w = frame.shape[:2]')
a('        self.frames_captured += 1')
a('')
a('    def get_command(self) -> RobotCommand:')
a('        """Get latest safe robot command. Non-blocking."""')
a('        with self._result_lock:')
a('            return self._latest_command')
a('')
a('    def get_detections(self) -> List[Detection]:')
a('        """Get latest tracked detections. Non-blocking."""')
a('        with self._result_lock:')
a('            return list(self._latest_detections)')
a('')
a('    def _inference_loop(self):')
a('        """Inference thread: process latest frame when available."""')
a('        last_time = time.monotonic()')
a('        while self._running:')
a('            # Get latest frame')
a('            with self._frame_lock:')
a('                frame = self._latest_frame')
a('                frame_id = self._frame_id')
a('')
a('            if frame is None or frame_id == self._last_processed_id:')
a('                time.sleep(0.001)')
a('                continue')
a('')
a('            # Thermal skip')
a('            skip = 0')
a('            if self.thermal:')
a('                skip = self.thermal.get_skip_factor()')
a('            if skip > 0 and frame_id % (skip + 1) != 0:')
a('                self.frames_skipped += 1')
a('                time.sleep(0.01)')
a('                continue')
a('')
a('            # Run detection')
a('            detections = self.detector.detect(frame)')
a('            self._last_processed_id = frame_id')
a('            self.frames_inferred += 1')
a('')
a('            # Feed watchdog')
a('            self.safety.feed_watchdog()')
a('')
a('            # Update tracker')
a('            tracks = self.tracker.update(detections)')
a('            tracked_dets = self.tracker.get_detections(tracks)')
a('')
a('            # Update shared state')
a('            with self._result_lock:')
a('                self._latest_detections = tracked_dets')
a('')
a('            # FPS')
a('            now = time.monotonic()')
a('            dt = now - last_time')
a('            if dt > 0:')
a('                self.inference_fps = 0.9 * self.inference_fps + 0.1 * (1.0 / dt)')
a('            last_time = now')
a('')
a('    def _control_loop(self):')
a('        """Control thread: runs at target_hz using Kalman predictions."""')
a('        period = 1.0 / self.target_hz')
a('        last_time = time.monotonic()')
a('')
a('        while self._running:')
a('            loop_start = time.monotonic()')
a('')
a('            # Get Kalman-predicted detections (fast, no inference)')
a('            predicted_tracks = self.tracker.predict()')
a('            predicted_dets = self.tracker.get_detections(predicted_tracks)')
a('')
a('            # Run controller')
a('            with self._result_lock:')
a('                img_w, img_h = self._img_w, self._img_h')
a('')
a('            raw_cmd = self.controller.update(predicted_dets, img_w, img_h)')
a('')
a('            # Safety filter')
a('            safe_cmd = self.safety.filter_command(raw_cmd, predicted_dets, img_w, img_h)')
a('')
a('            with self._result_lock:')
a('                self._latest_command = safe_cmd')
a('                self._latest_detections = predicted_dets')
a('')
a('            # FPS')
a('            now = time.monotonic()')
a('            dt = now - last_time')
a('            if dt > 0:')
a('                self.control_fps = 0.9 * self.control_fps + 0.1 * (1.0 / dt)')
a('            last_time = now')
a('')
a('            # Sleep to maintain target rate')
a('            elapsed = time.monotonic() - loop_start')
a('            sleep_time = period - elapsed')
a('            if sleep_time > 0:')
a('                time.sleep(sleep_time)')
a('')
a('    def start(self):')
a('        """Start inference and control threads."""')
a('        self._running = True')
a('        if self.thermal:')
a('            self.thermal.start()')
a('')
a('        t_inf = threading.Thread(target=self._inference_loop, daemon=True, name="inference")')
a('        t_ctrl = threading.Thread(target=self._control_loop, daemon=True, name="control")')
a('        t_inf.start()')
a('        t_ctrl.start()')
a('        self._threads = [t_inf, t_ctrl]')
a('        logger.info("AsyncPipeline started: inference + control threads")')
a('')
a('    def stop(self):')
a('        self._running = False')
a('        if self.thermal:')
a('            self.thermal.stop()')
a('        for t in self._threads:')
a('            t.join(timeout=5)')
a('        logger.info("AsyncPipeline stopped")')
a('')
a('    def get_status(self) -> dict:')
a('        return {')
a('            "inference_fps": round(self.inference_fps, 1),')
a('            "control_fps": round(self.control_fps, 1),')
a('            "frames_captured": self.frames_captured,')
a('            "frames_inferred": self.frames_inferred,')
a('            "frames_skipped": self.frames_skipped,')
a('            "tracker": self.tracker.get_status(),')
a('            "safety": self.safety.get_status(),')
a('        }')

print(f"Part 2 (Tracking + Async): {len(lines)} lines")
with open('edge_ai_v2.py', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print("edge_ai_v2.py Part 2 appended")
