lines = []
a = lines.append

a('')
a('')
a('# ================================================================')
a('# TIER 3: FIELD DEBUGGING')
a('# ================================================================')
a('')
a('')
a('class BlackBoxRecorder:')
a('    """')
a('    Flight-recorder style logging for robot debugging.')
a('')
a('    Records to a binary log file:')
a('      - Timestamped detections')
a('      - Robot commands')
a('      - Safety events')
a('      - Image quality scores')
a('      - System metrics (temp, memory, FPS)')
a('')
a('    Supports:')
a('      - Circular buffer (fixed max size, overwrites oldest)')
a('      - JSON export for analysis')
a('      - Frame snapshots on events (e-stop, timeout)')
a('      - Replay: load log and feed to controller')
a('    """')
a('')
a('    def __init__(self,')
a('                 log_dir: str = "blackbox",')
a('                 max_entries: int = 10000,')
a('                 save_frames_on_event: bool = True,')
a('                 max_frame_snapshots: int = 100):')
a('        self.log_dir = log_dir')
a('        self.max_entries = max_entries')
a('        self.save_frames_on_event = save_frames_on_event')
a('        self.max_frame_snapshots = max_frame_snapshots')
a('')
a('        self.entries = deque(maxlen=max_entries)')
a('        self.frame_snapshots = deque(maxlen=max_frame_snapshots)')
a('        self.start_time = time.monotonic()')
a('        self.session_id = time.strftime("%Y%m%d_%H%M%S")')
a('        self._entry_count = 0')
a('')
a('        os.makedirs(log_dir, exist_ok=True)')
a('')
a('    def record(self, entry_type: str, data: dict, frame: np.ndarray = None):')
a('        """Record a timestamped entry."""')
a('        entry = {')
a('            "t": time.monotonic() - self.start_time,')
a('            "wall": time.time(),')
a('            "seq": self._entry_count,')
a('            "type": entry_type,')
a('            "data": data,')
a('        }')
a('        self.entries.append(entry)')
a('        self._entry_count += 1')
a('')
a('        # Save frame snapshot on important events')
a('        if frame is not None and self.save_frames_on_event:')
a('            if entry_type in ("estop", "timeout", "critical", "proximity_stop", "quality_alert"):')
a('                self.frame_snapshots.append({')
a('                    "seq": entry["seq"],')
a('                    "t": entry["t"],')
a('                    "type": entry_type,')
a('                    "frame_shape": frame.shape,')
a('                })')
a('                # Save frame as numpy file')
a('                try:')
a('                    fname = os.path.join(self.log_dir, f"frame_{entry[\'seq\']:06d}.npy")')
a('                    np.save(fname, frame)')
a('                except Exception as e:')
a('                    logger.warning(f"Failed to save frame: {e}")')
a('')
a('    def record_detection(self, detections: list, inference_ms: float):')
a('        self.record("detection", {')
a('            "count": len(detections),')
a('            "objects": [{"class": d.class_name, "conf": round(d.confidence, 3),')
a('                         "bbox": [round(d.x1, 1), round(d.y1, 1), round(d.x2, 1), round(d.y2, 1)]')
a('                        } for d in detections[:20]],')
a('            "inference_ms": round(inference_ms, 1),')
a('        })')
a('')
a('    def record_command(self, cmd: RobotCommand):')
a('        self.record("command", {')
a('            "linear_x": round(cmd.linear_x, 4),')
a('            "angular_z": round(cmd.angular_z, 4),')
a('            "action": cmd.action,')
a('            "description": cmd.description,')
a('        })')
a('')
a('    def record_safety_event(self, event_type: str, detail: str, frame: np.ndarray = None):')
a('        self.record(event_type, {"detail": detail}, frame=frame)')
a('')
a('    def record_metrics(self, metrics: dict):')
a('        self.record("metrics", metrics)')
a('')
a('    def save(self, filename: str = None) -> str:')
a('        """Save log to JSON file. Returns filepath."""')
a('        if filename is None:')
a('            filename = f"blackbox_{self.session_id}.json"')
a('        filepath = os.path.join(self.log_dir, filename)')
a('')
a('        log_data = {')
a('            "session_id": self.session_id,')
a('            "total_entries": self._entry_count,')
a('            "saved_entries": len(self.entries),')
a('            "duration_s": time.monotonic() - self.start_time,')
a('            "frame_snapshots": len(self.frame_snapshots),')
a('            "entries": list(self.entries),')
a('        }')
a('')
a('        with open(filepath, "w") as f:')
a('            json.dump(log_data, f, indent=2, default=str)')
a('')
a('        logger.info(f"Black box saved: {filepath} ({len(self.entries)} entries)")')
a('        return filepath')
a('')
a('    @staticmethod')
a('    def load(filepath: str) -> dict:')
a('        """Load a saved black box log."""')
a('        with open(filepath) as f:')
a('            return json.load(f)')
a('')
a('    def get_recent(self, n: int = 20, entry_type: str = None) -> list:')
a('        """Get last N entries, optionally filtered by type."""')
a('        if entry_type:')
a('            filtered = [e for e in self.entries if e["type"] == entry_type]')
a('            return list(filtered)[-n:]')
a('        return list(self.entries)[-n:]')
a('')
a('    def get_status(self) -> dict:')
a('        return {')
a('            "session_id": self.session_id,')
a('            "total_entries": self._entry_count,')
a('            "buffer_used": len(self.entries),')
a('            "buffer_max": self.max_entries,')
a('            "frame_snapshots": len(self.frame_snapshots),')
a('            "duration_s": round(time.monotonic() - self.start_time, 1),')
a('        }')
a('')
a('')
a('class ImageQualityScorer:')
a('    """')
a('    Fast image quality assessment for camera health monitoring.')
a('')
a('    Detects:')
a('      - Blur (Laplacian variance)')
a('      - Darkness / overexposure (histogram analysis)')
a('      - Low contrast (histogram spread)')
a('      - Occlusion (uniform regions)')
a('')
a('    Returns quality score 0-100 and per-issue flags.')
a('    All computed with numpy only (no OpenCV required).')
a('    """')
a('')
a('    def __init__(self,')
a('                 blur_threshold: float = 50.0,')
a('                 dark_threshold: float = 40.0,')
a('                 bright_threshold: float = 220.0,')
a('                 contrast_threshold: float = 30.0):')
a('        self.blur_threshold = blur_threshold')
a('        self.dark_threshold = dark_threshold')
a('        self.bright_threshold = bright_threshold')
a('        self.contrast_threshold = contrast_threshold')
a('        self.history = deque(maxlen=100)')
a('')
a('    def score(self, image: np.ndarray) -> dict:')
a('        """')
a('        Score image quality.')
a('')
a('        Returns:')
a('            {"score": 0-100, "blur": float, "brightness": float,')
a('             "contrast": float, "issues": ["dark", "blurry", ...],')
a('             "usable": bool}')
a('        """')
a('        if image is None or image.size == 0:')
a('            return {"score": 0, "issues": ["no_image"], "usable": False,')
a('                    "blur": 0, "brightness": 0, "contrast": 0}')
a('')
a('        # Convert to grayscale if needed')
a('        if image.ndim == 3:')
a('            gray = np.mean(image, axis=2).astype(np.float32)')
a('        else:')
a('            gray = image.astype(np.float32)')
a('')
a('        # Downsample for speed')
a('        h, w = gray.shape')
a('        if h > 120:')
a('            step = h // 120')
a('            gray = gray[::step, ::step]')
a('')
a('        issues = []')
a('        scores = []')
a('')
a('        # 1. Blur detection (Laplacian variance)')
a('        # Laplacian kernel: [[0,1,0],[1,-4,1],[0,1,0]]')
a('        laplacian = np.zeros_like(gray)')
a('        laplacian[1:-1, 1:-1] = (')
a('            gray[0:-2, 1:-1] + gray[2:, 1:-1] +')
a('            gray[1:-1, 0:-2] + gray[1:-1, 2:] -')
a('            4 * gray[1:-1, 1:-1]')
a('        )')
a('        blur_score = float(np.var(laplacian))')
a('        if blur_score < self.blur_threshold:')
a('            issues.append("blurry")')
a('        blur_quality = min(100, blur_score / self.blur_threshold * 100)')
a('        scores.append(blur_quality)')
a('')
a('        # 2. Brightness')
a('        mean_brightness = float(np.mean(gray))')
a('        if mean_brightness < self.dark_threshold:')
a('            issues.append("dark")')
a('            bright_quality = mean_brightness / self.dark_threshold * 100')
a('        elif mean_brightness > self.bright_threshold:')
a('            issues.append("overexposed")')
a('            bright_quality = max(0, (255 - mean_brightness) / (255 - self.bright_threshold) * 100)')
a('        else:')
a('            bright_quality = 100')
a('        scores.append(bright_quality)')
a('')
a('        # 3. Contrast (std dev of brightness)')
a('        contrast = float(np.std(gray))')
a('        if contrast < self.contrast_threshold:')
a('            issues.append("low_contrast")')
a('        contrast_quality = min(100, contrast / self.contrast_threshold * 100)')
a('        scores.append(contrast_quality)')
a('')
a('        # 4. Uniform region detection (possible occlusion)')
a('        # Check if >50% of image is very similar')
a('        hist_range = np.ptp(gray)  # peak to peak')
a('        if hist_range < 15:')
a('            issues.append("occluded")')
a('            scores.append(20)')
a('        else:')
a('            scores.append(100)')
a('')
a('        # Overall score')
a('        overall = float(np.mean(scores))')
a('        usable = overall > 40 and "occluded" not in issues')
a('')
a('        result = {')
a('            "score": round(overall, 1),')
a('            "blur": round(blur_score, 1),')
a('            "brightness": round(mean_brightness, 1),')
a('            "contrast": round(contrast, 1),')
a('            "issues": issues,')
a('            "usable": usable,')
a('        }')
a('        self.history.append(result)')
a('        return result')
a('')
a('    def get_trend(self) -> dict:')
a('        """Get quality trend over recent frames."""')
a('        if not self.history:')
a('            return {"avg_score": 0, "degrading": False, "samples": 0}')
a('')
a('        recent = list(self.history)')
a('        scores = [r["score"] for r in recent]')
a('        avg = np.mean(scores)')
a('')
a('        # Check if degrading (last 10 worse than first 10)')
a('        degrading = False')
a('        if len(scores) > 20:')
a('            early = np.mean(scores[:10])')
a('            late = np.mean(scores[-10:])')
a('            degrading = late < early * 0.8  # 20% worse')
a('')
a('        return {')
a('            "avg_score": round(float(avg), 1),')
a('            "min_score": round(float(min(scores)), 1),')
a('            "degrading": degrading,')
a('            "samples": len(scores),')
a('            "issue_counts": {')
a('                issue: sum(1 for r in recent if issue in r["issues"])')
a('                for issue in ("blurry", "dark", "overexposed", "low_contrast", "occluded")'),
a('            },')
a('        }')
a('')
a('')
a('# ================================================================')
a('# PRODUCTION EDGE AI - PUTS IT ALL TOGETHER')
a('# ================================================================')
a('')
a('')
a('class ProductionEdgeAI:')
a('    """')
a('    Production-ready edge AI pipeline.')
a('')
a('    Integrates all tiers:')
a('      - Safety controller (e-stop, watchdog, ramping)')
a('      - Thermal monitor (auto-throttle)')
a('      - Memory watchdog (OOM prevention)')
a('      - Object tracker (persistent IDs, Kalman prediction)')
a('      - Async pipeline (30Hz control from 2 FPS vision)')
a('      - Black box recorder (field debugging)')
a('      - Image quality scorer (sensor health)')
a('')
a('    Usage:')
a('      ai = ProductionEdgeAI.auto(mode="follow", target="person")')
a('      ai.start()')
a('      while running:')
a('          ai.push_frame(camera_frame)')
a('          cmd = ai.get_command()')
a('          robot.set_velocity(cmd.linear_x, cmd.angular_z)')
a('      ai.stop()')
a('    """')
a('')
a('    def __init__(self,')
a('                 detector: ObjectDetector,')
a('                 controller: RobotController,')
a('                 safety: SafetyController = None,')
a('                 thermal: ThermalMonitor = None,')
a('                 memory: MemoryWatchdog = None,')
a('                 tracker: ObjectTracker = None,')
a('                 recorder: BlackBoxRecorder = None,')
a('                 quality: ImageQualityScorer = None,')
a('                 target_hz: float = 30.0):')
a('')
a('        self.detector = detector')
a('        self.controller = controller')
a('        self.safety = safety or SafetyController()')
a('        self.thermal = thermal or ThermalMonitor()')
a('        self.memory = memory or MemoryWatchdog(on_critical=lambda: self.safety.estop("OOM_imminent"))')
a('        self.tracker = tracker or ObjectTracker()')
a('        self.recorder = recorder or BlackBoxRecorder()')
a('        self.quality = quality or ImageQualityScorer()')
a('')
a('        self.pipeline = AsyncPipeline(')
a('            detector=detector,')
a('            controller=controller,')
a('            tracker=self.tracker,')
a('            safety=self.safety,')
a('            thermal=self.thermal,')
a('            target_hz=target_hz,')
a('        )')
a('')
a('        self._metrics_interval = 5.0  # log metrics every 5s')
a('        self._last_metrics = 0')
a('        self._frame_count = 0')
a('')
a('    @classmethod')
a('    def auto(cls,')
a('             mode: str = "follow",')
a('             target: str = "person",')
a('             model_path: str = None,')
a('             conf_thresh: float = 0.4,')
a('             max_linear: float = 0.3,')
a('             max_angular: float = 0.5,')
a('             target_hz: float = 30.0):')
a('        """Auto-configure everything based on hardware."""')
a('')
a('        detector = ObjectDetector.auto(task="detect", conf_thresh=conf_thresh)')
a('        controller = RobotController(mode=mode, target_classes=[target],')
a('                                      max_linear=max_linear, max_angular=max_angular)')
a('        safety = SafetyController(max_linear=max_linear, max_angular=max_angular)')
a('')
a('        return cls(')
a('            detector=detector,')
a('            controller=controller,')
a('            safety=safety,')
a('            target_hz=target_hz,')
a('        )')
a('')
a('    def start(self):')
a('        """Start all background threads."""')
a('        self.thermal.start()')
a('        self.memory.start()')
a('        self.pipeline.start()')
a('        logger.info("ProductionEdgeAI started")')
a('')
a('    def stop(self):')
a('        """Stop everything and save black box."""')
a('        self.pipeline.stop()')
a('        self.thermal.stop()')
a('        self.memory.stop()')
a('        filepath = self.recorder.save()')
a('        logger.info(f"ProductionEdgeAI stopped. Black box: {filepath}")')
a('        return filepath')
a('')
a('    def push_frame(self, frame: np.ndarray):')
a('        """Push camera frame. Also checks image quality."""')
a('        self._frame_count += 1')
a('')
a('        # Quality check (every 10th frame to save CPU)')
a('        if self._frame_count % 10 == 0:')
a('            q = self.quality.score(frame)')
a('            if not q["usable"]:')
a('                self.recorder.record_safety_event(')
a('                    "quality_alert",')
a('                    f"Image unusable: {q[\'issues\']}, score={q[\'score\']}",')
a('                    frame=frame')
a('                )')
a('')
a('        self.pipeline.push_frame(frame)')
a('')
a('        # Periodic metrics logging')
a('        now = time.monotonic()')
a('        if now - self._last_metrics > self._metrics_interval:')
a('            self._log_metrics()')
a('            self._last_metrics = now')
a('')
a('    def get_command(self) -> RobotCommand:')
a('        """Get latest safe robot command."""')
a('        cmd = self.pipeline.get_command()')
a('        self.recorder.record_command(cmd)')
a('        return cmd')
a('')
a('    def get_detections(self) -> List[Detection]:')
a('        """Get latest tracked detections."""')
a('        return self.pipeline.get_detections()')
a('')
a('    def estop(self, reason: str = "manual"):')
a('        """Emergency stop."""')
a('        self.safety.estop(reason)')
a('        self.recorder.record_safety_event("estop", reason)')
a('')
a('    def reset(self):')
a('        """Clear e-stop."""')
a('        self.safety.reset()')
a('        self.recorder.record_safety_event("reset", "E-stop cleared")')
a('')
a('    def _log_metrics(self):')
a('        metrics = {')
a('            "pipeline": self.pipeline.get_status(),')
a('            "thermal": self.thermal.get_status(),')
a('            "memory": self.memory.get_status(),')
a('            "quality": self.quality.get_trend(),')
a('            "recorder": self.recorder.get_status(),')
a('        }')
a('        self.recorder.record_metrics(metrics)')
a('')
a('    def get_full_status(self) -> dict:')
a('        """Get complete system status for dashboard/telemetry."""')
a('        return {')
a('            "safety": self.safety.get_status(),')
a('            "thermal": self.thermal.get_status(),')
a('            "memory": self.memory.get_status(),')
a('            "pipeline": self.pipeline.get_status(),')
a('            "quality": self.quality.get_trend(),')
a('            "recorder": self.recorder.get_status(),')
a('            "tracker": self.tracker.get_status(),')
a('        }')
a('')
a('    def process_sync(self, frame: np.ndarray) -> dict:')
a('        """')
a('        Synchronous processing (no threads needed).')
a('        For testing or simple loops.')
a('')
a('        Returns: {"detections", "tracks", "command", "quality", "safety_state"}')
a('        """')
a('        # Quality check')
a('        q = self.quality.score(frame)')
a('')
a('        # Detect')
a('        detections = self.detector.detect(frame)')
a('        self.safety.feed_watchdog()')
a('')
a('        # Track')
a('        tracks = self.tracker.update(detections)')
a('        tracked_dets = self.tracker.get_detections(tracks)')
a('')
a('        # Control')
a('        h, w = frame.shape[:2]')
a('        raw_cmd = self.controller.update(tracked_dets, w, h)')
a('        safe_cmd = self.safety.filter_command(raw_cmd, tracked_dets, w, h)')
a('')
a('        # Record')
a('        self.recorder.record_detection(detections, self.detector.avg_ms)')
a('        self.recorder.record_command(safe_cmd)')
a('')
a('        return {')
a('            "detections": detections,')
a('            "tracks": [{"id": t.track_id, "class": t.class_name,')
a('                        "confidence": t.confidence, "frames_seen": t.frames_seen}')
a('                       for t in tracks],')
a('            "command": safe_cmd,')
a('            "quality": q,')
a('            "safety_state": self.safety.state,')
a('            "fps": self.detector.fps,')
a('            "avg_ms": self.detector.avg_ms,')
a('        }')

print(f"Part 3 (Debug + Production): {len(lines)} lines")
with open('edge_ai_v2.py', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print("edge_ai_v2.py Part 3 appended")

# Final check
with open('edge_ai_v2.py', 'r') as f:
    content = f.read()
lcount = content.count('\n')
print(f"\nFinal: {len(content)} bytes, {lcount} lines")

classes = ['SafetyController', 'ThermalMonitor', 'MemoryWatchdog',
           'KalmanFilter2D', 'TrackedObject', 'ObjectTracker', 'AsyncPipeline',
           'BlackBoxRecorder', 'ImageQualityScorer', 'ProductionEdgeAI']
for c in classes:
    found = f'class {c}' in content
    print(f"  {'[OK]' if found else '[MISSING]'} {c}")
