lines = []
a = lines.append

a('"""')
a('TinyTPU Edge AI v2 - Production Safety & Tracking Layer')
a('=========================================================')
a('Extends edge_ai.py with production-critical features:')
a('')
a('Tier 1 - Safety:')
a('  SafetyController  - E-stop, watchdog, velocity ramping, detection timeout')
a('  ThermalMonitor    - CPU temp polling, auto-throttle before OS thermal cliff')
a('  MemoryWatchdog    - RSS tracking, OOM prevention')
a('')
a('Tier 2 - Tracking:')
a('  KalmanFilter2D    - Predict object positions between inference frames')
a('  TrackedObject     - Persistent object with ID, history, Kalman state')
a('  ObjectTracker     - IoU matching + Kalman prediction, 30Hz from 2FPS vision')
a('  AsyncPipeline     - Threaded capture/inference/control, nothing blocks')
a('')
a('Tier 3 - Field Debugging:')
a('  BlackBoxRecorder  - Log detections + commands + frames, replay offline')
a('  ImageQualityScorer - Detect blur/darkness/occlusion')
a('')
a('Usage:')
a('  from tinytpu.edge_ai_v2 import SafetyController, ThermalMonitor, MemoryWatchdog')
a('  from tinytpu.edge_ai_v2 import ObjectTracker, AsyncPipeline')
a('  from tinytpu.edge_ai_v2 import BlackBoxRecorder, ImageQualityScorer')
a('  from tinytpu.edge_ai_v2 import ProductionEdgeAI')
a('"""')
a('')
a('import os, sys, time, threading, json, struct, logging')
a('from dataclasses import dataclass, field')
a('from typing import List, Dict, Optional, Tuple, Any')
a('from collections import deque')
a('import numpy as np')
a('')
a('from tinytpu.edge_ai import Detection, RobotCommand, ObjectDetector, RobotController, EdgeAI, detect_hardware')
a('')
a('logger = logging.getLogger("tinytpu.edge_ai_v2")')
a('')
a('')
a('# ================================================================')
a('# TIER 1: SAFETY')
a('# ================================================================')
a('')
a('')
a('class SafetyController:')
a('    """')
a('    Production safety layer between perception and motors.')
a('')
a('    Features:')
a('      - Software E-stop (immediate zero velocity)')
a('      - Watchdog timer (no detection update -> safe stop)')
a('      - Velocity ramping (no instant max speed)')
a('      - Detection timeout (vision failure -> stop)')
a('      - Max velocity enforcement (hardware limits)')
a('      - Collision proximity stop (object too close)')
a('      - State machine: RUNNING -> ESTOP | TIMEOUT | RAMPING_DOWN')
a('    """')
a('')
a('    RUNNING = "running"')
a('    ESTOP = "estop"')
a('    TIMEOUT = "timeout"')
a('    RAMPING_DOWN = "ramping_down"')
a('    STARTUP = "startup"')
a('')
a('    def __init__(self,')
a('                 max_linear: float = 0.3,')
a('                 max_angular: float = 0.5,')
a('                 watchdog_timeout: float = 2.0,')
a('                 ramp_rate: float = 0.5,')
a('                 min_proximity: float = 0.15,')
a('                 startup_delay: float = 1.0):')
a('        """')
a('        Args:')
a('            max_linear: Hard limit on linear velocity (m/s)')
a('            max_angular: Hard limit on angular velocity (rad/s)')
a('            watchdog_timeout: Seconds without detection update before safe stop')
a('            ramp_rate: Max velocity change per second (m/s/s)')
a('            min_proximity: Object relative size that triggers emergency stop')
a('            startup_delay: Seconds to wait before allowing movement')
a('        """')
a('        self.max_linear = max_linear')
a('        self.max_angular = max_angular')
a('        self.watchdog_timeout = watchdog_timeout')
a('        self.ramp_rate = ramp_rate')
a('        self.min_proximity = min_proximity')
a('        self.startup_delay = startup_delay')
a('')
a('        self.state = self.STARTUP')
a('        self.estop_active = False')
a('        self.last_detection_time = time.monotonic()')
a('        self.last_command_time = time.monotonic()')
a('        self.startup_time = time.monotonic()')
a('        self.current_linear = 0.0')
a('        self.current_angular = 0.0')
a('')
a('        # Telemetry')
a('        self.estop_count = 0')
a('        self.timeout_count = 0')
a('        self.proximity_stop_count = 0')
a('        self.total_commands = 0')
a('        self.violations = []  # list of (time, type, detail)')
a('')
a('        self._lock = threading.Lock()')
a('')
a('    def estop(self, reason: str = "manual"):')
a('        """Immediate stop. Must call reset() to resume."""')
a('        with self._lock:')
a('            self.estop_active = True')
a('            self.state = self.ESTOP')
a('            self.current_linear = 0.0')
a('            self.current_angular = 0.0')
a('            self.estop_count += 1')
a('            self.violations.append((time.monotonic(), "estop", reason))')
a('            logger.warning(f"E-STOP activated: {reason}")')
a('')
a('    def reset(self):')
a('        """Clear E-stop. Robot will ramp up from zero."""')
a('        with self._lock:')
a('            self.estop_active = False')
a('            self.state = self.RUNNING')
a('            self.current_linear = 0.0')
a('            self.current_angular = 0.0')
a('            self.last_detection_time = time.monotonic()')
a('            logger.info("E-STOP cleared, resuming")')
a('')
a('    def feed_watchdog(self):')
a('        """Call this every time a valid detection frame arrives."""')
a('        self.last_detection_time = time.monotonic()')
a('')
a('    def _check_proximity(self, detections: list, img_w: int, img_h: int) -> bool:')
a('        """Return True if any object is dangerously close."""')
a('        img_area = img_w * img_h')
a('        if img_area == 0:')
a('            return False')
a('        for det in detections:')
a('            relative_size = det.area / img_area')
a('            if relative_size > self.min_proximity:')
a('                return True')
a('        return False')
a('')
a('    def filter_command(self, cmd: RobotCommand, detections: list = None,')
a('                       img_w: int = 640, img_h: int = 480) -> RobotCommand:')
a('        """')
a('        Filter a robot command through safety checks.')
a('')
a('        Returns a safe command (possibly zeroed).')
a('        """')
a('        now = time.monotonic()')
a('        self.total_commands += 1')
a('')
a('        with self._lock:')
a('            # 1. E-stop check')
a('            if self.estop_active:')
a('                return RobotCommand(0, 0, 0, "estop", "E-STOP active")')
a('')
a('            # 2. Startup delay')
a('            if now - self.startup_time < self.startup_delay:')
a('                self.state = self.STARTUP')
a('                return RobotCommand(0, 0, 0, "startup", f"Starting in {self.startup_delay-(now-self.startup_time):.1f}s")')
a('')
a('            # 3. Watchdog timeout')
a('            since_detection = now - self.last_detection_time')
a('            if since_detection > self.watchdog_timeout:')
a('                if self.state != self.TIMEOUT:')
a('                    self.timeout_count += 1')
a('                    self.violations.append((now, "timeout", f"{since_detection:.1f}s without detection"))')
a('                    logger.warning(f"Watchdog timeout: {since_detection:.1f}s without detection")')
a('                self.state = self.TIMEOUT')
a('                self.current_linear = 0.0')
a('                self.current_angular = 0.0')
a('                return RobotCommand(0, 0, 0, "timeout", f"No detection for {since_detection:.1f}s")')
a('')
a('            # 4. Proximity check')
a('            if detections and self._check_proximity(detections, img_w, img_h):')
a('                self.proximity_stop_count += 1')
a('                self.current_linear = 0.0')
a('                return RobotCommand(0, 0, cmd.angular_z * 0.5, "proximity_stop", "Object too close")')
a('')
a('            # 5. Enforce velocity limits')
a('            target_linear = max(-self.max_linear, min(self.max_linear, cmd.linear_x))')
a('            target_angular = max(-self.max_angular, min(self.max_angular, cmd.angular_z))')
a('')
a('            # 6. Velocity ramping')
a('            dt = now - self.last_command_time')
a('            dt = min(dt, 0.5)  # cap for first call or long gaps')
a('            max_change = self.ramp_rate * dt')
a('')
a('            if target_linear > self.current_linear:')
a('                self.current_linear = min(target_linear, self.current_linear + max_change)')
a('            else:')
a('                self.current_linear = max(target_linear, self.current_linear - max_change * 2)  # brake faster')
a('')
a('            if target_angular > self.current_angular:')
a('                self.current_angular = min(target_angular, self.current_angular + max_change * 2)')
a('            else:')
a('                self.current_angular = max(target_angular, self.current_angular - max_change * 2)')
a('')
a('            self.last_command_time = now')
a('            self.state = self.RUNNING')
a('')
a('            return RobotCommand(self.current_linear, cmd.linear_y, self.current_angular,')
a('                               cmd.action, cmd.description)')
a('')
a('    def get_status(self) -> dict:')
a('        """Return safety system status for telemetry."""')
a('        now = time.monotonic()')
a('        return {')
a('            "state": self.state,')
a('            "estop_active": self.estop_active,')
a('            "seconds_since_detection": now - self.last_detection_time,')
a('            "current_linear": self.current_linear,')
a('            "current_angular": self.current_angular,')
a('            "estop_count": self.estop_count,')
a('            "timeout_count": self.timeout_count,')
a('            "proximity_stops": self.proximity_stop_count,')
a('            "total_commands": self.total_commands,')
a('            "recent_violations": self.violations[-10:],')
a('        }')
a('')
a('')
a('class ThermalMonitor:')
a('    """')
a('    CPU temperature monitoring with auto-throttle.')
a('')
a('    Problem: RPi4 hits 80C in ~50s of inference, OS throttles')
a('    clock from 1.5GHz to 1GHz = 40% perf drop without warning.')
a('')
a('    Solution: Monitor temp, proactively reduce inference rate')
a('    before the OS thermal cliff.')
a('    """')
a('')
a('    def __init__(self,')
a('                 warn_temp: float = 70.0,')
a('                 critical_temp: float = 78.0,')
a('                 shutdown_temp: float = 85.0,')
a('                 poll_interval: float = 2.0):')
a('        self.warn_temp = warn_temp')
a('        self.critical_temp = critical_temp')
a('        self.shutdown_temp = shutdown_temp')
a('        self.poll_interval = poll_interval')
a('')
a('        self.current_temp = 0.0')
a('        self.max_temp = 0.0')
a('        self.throttle_level = 0  # 0=none, 1=warn, 2=critical, 3=shutdown')
a('        self.temp_history = deque(maxlen=300)  # 10 min at 2s interval')
a('        self.throttle_events = []')
a('')
a('        self._running = False')
a('        self._thread = None')
a('')
a('    def _read_temp(self) -> float:')
a('        """Read CPU temperature. Cross-platform."""')
a('        # Linux: thermal zone')
a('        try:')
a('            with open("/sys/class/thermal/thermal_zone0/temp") as f:')
a('                return float(f.read().strip()) / 1000.0')
a('        except (FileNotFoundError, PermissionError):')
a('            pass')
a('')
a('        # Raspberry Pi: vcgencmd')
a('        try:')
a('            import subprocess')
a('            result = subprocess.run(["vcgencmd", "measure_temp"],')
a('                                   capture_output=True, text=True, timeout=2)')
a('            if result.returncode == 0:')
a('                # "temp=45.0\'C"')
a('                return float(result.stdout.split("=")[1].split("\'")[0])')
a('        except (FileNotFoundError, Exception):')
a('            pass')
a('')
a('        # Windows: WMI (rough)')
a('        try:')
a('            import subprocess')
a('            result = subprocess.run(')
a('                ["wmic", "path", "MSAcpi_ThermalZoneTemperature", "get", "CurrentTemperature"],')
a('                capture_output=True, text=True, timeout=5)')
a('            for line in result.stdout.strip().split("\\n"):')
a('                line = line.strip()')
a('                if line.isdigit():')
a('                    return (float(line) - 2732) / 10.0  # decikelvin to C')
a('        except Exception:')
a('            pass')
a('')
a('        return -1.0  # unknown')
a('')
a('    def _poll_loop(self):')
a('        while self._running:')
a('            temp = self._read_temp()')
a('            if temp > 0:')
a('                self.current_temp = temp')
a('                self.max_temp = max(self.max_temp, temp)')
a('                self.temp_history.append((time.monotonic(), temp))')
a('')
a('                old_level = self.throttle_level')
a('                if temp >= self.shutdown_temp:')
a('                    self.throttle_level = 3')
a('                elif temp >= self.critical_temp:')
a('                    self.throttle_level = 2')
a('                elif temp >= self.warn_temp:')
a('                    self.throttle_level = 1')
a('                else:')
a('                    self.throttle_level = 0')
a('')
a('                if self.throttle_level != old_level and self.throttle_level > 0:')
a('                    event = (time.monotonic(), temp, self.throttle_level)')
a('                    self.throttle_events.append(event)')
a('                    labels = {1: "WARN", 2: "CRITICAL", 3: "SHUTDOWN"}')
a('                    logger.warning(f"Thermal {labels[self.throttle_level]}: {temp:.1f}C")')
a('')
a('            time.sleep(self.poll_interval)')
a('')
a('    def start(self):')
a('        """Start background temperature monitoring."""')
a('        self._running = True')
a('        self._thread = threading.Thread(target=self._poll_loop, daemon=True, name="thermal_monitor")')
a('        self._thread.start()')
a('')
a('    def stop(self):')
a('        self._running = False')
a('        if self._thread:')
a('            self._thread.join(timeout=5)')
a('')
a('    def get_skip_factor(self) -> int:')
a('        """How many frames to skip based on thermal state.')
a('        0 = process every frame, 1 = skip every other, etc."""')
a('        if self.throttle_level == 0:')
a('            return 0  # full speed')
a('        elif self.throttle_level == 1:')
a('            return 1  # skip every other frame')
a('        elif self.throttle_level == 2:')
a('            return 2  # process every 3rd frame')
a('        else:')
a('            return 4  # minimal inference, near shutdown')
a('')
a('    def get_status(self) -> dict:')
a('        return {')
a('            "current_temp_c": self.current_temp,')
a('            "max_temp_c": self.max_temp,')
a('            "throttle_level": self.throttle_level,')
a('            "throttle_label": ["none", "warn", "critical", "shutdown"][self.throttle_level],')
a('            "skip_factor": self.get_skip_factor(),')
a('            "history_len": len(self.temp_history),')
a('            "throttle_events": len(self.throttle_events),')
a('        }')
a('')
a('')
a('class MemoryWatchdog:')
a('    """')
a('    Monitor process RSS and system memory.')
a('')
a('    Problem: YOLO on Pi 2GB silently crashes after ~20min.')
a('    No error, no log, just dies. OOM killer strikes.')
a('')
a('    Solution: Track memory, warn early, force GC, and')
a('    optionally trigger safe stop before OOM.')
a('    """')
a('')
a('    def __init__(self,')
a('                 warn_percent: float = 70.0,')
a('                 critical_percent: float = 85.0,')
a('                 max_rss_mb: float = 0,')
a('                 poll_interval: float = 5.0,')
a('                 on_critical=None):')
a('        """')
a('        Args:')
a('            warn_percent: System RAM usage % to trigger warning')
a('            critical_percent: System RAM usage % to trigger critical action')
a('            max_rss_mb: Max process RSS in MB (0 = auto: 50% of total)')
a('            poll_interval: Seconds between checks')
a('            on_critical: Callback when critical threshold hit')
a('        """')
a('        self.warn_percent = warn_percent')
a('        self.critical_percent = critical_percent')
a('        self.max_rss_mb = max_rss_mb')
a('        self.poll_interval = poll_interval')
a('        self.on_critical = on_critical')
a('')
a('        self.current_rss_mb = 0.0')
a('        self.peak_rss_mb = 0.0')
a('        self.system_used_percent = 0.0')
a('        self.system_available_mb = 0.0')
a('        self.state = "ok"  # ok, warn, critical')
a('        self.events = []')
a('        self.rss_history = deque(maxlen=120)  # 10 min at 5s')
a('')
a('        self._running = False')
a('        self._thread = None')
a('')
a('        # Auto-detect max RSS if not set')
a('        if self.max_rss_mb == 0:')
a('            hw = detect_hardware()')
a('            self.max_rss_mb = hw.ram_total_mb * 0.5')
a('')
a('    def _read_memory(self):')
a('        """Read process and system memory."""')
a('        # Process RSS')
a('        try:')
a('            with open(f"/proc/{os.getpid()}/status") as f:')
a('                for line in f:')
a('                    if line.startswith("VmRSS:"):')
a('                        self.current_rss_mb = float(line.split()[1]) / 1024.0')
a('                        break')
a('        except (FileNotFoundError, PermissionError):')
a('            try:')
a('                import psutil')
a('                proc = psutil.Process(os.getpid())')
a('                self.current_rss_mb = proc.memory_info().rss / 1024 / 1024')
a('            except ImportError:')
a('                pass')
a('')
a('        self.peak_rss_mb = max(self.peak_rss_mb, self.current_rss_mb)')
a('')
a('        # System memory')
a('        try:')
a('            with open("/proc/meminfo") as f:')
a('                info = {}')
a('                for line in f:')
a('                    parts = line.split()')
a('                    if len(parts) >= 2:')
a('                        info[parts[0].rstrip(":")] = int(parts[1])')
a('                total = info.get("MemTotal", 1) / 1024')
a('                avail = info.get("MemAvailable", info.get("MemFree", 0)) / 1024')
a('                self.system_available_mb = avail')
a('                self.system_used_percent = (1 - avail / total) * 100 if total > 0 else 0')
a('        except (FileNotFoundError, PermissionError):')
a('            try:')
a('                import ctypes')
a('                class MEMSTAT(ctypes.Structure):')
a('                    _fields_ = [("dwLength", ctypes.c_ulong),')
a('                                ("dwMemoryLoad", ctypes.c_ulong),')
a('                                ("ullTotalPhys", ctypes.c_ulonglong),')
a('                                ("ullAvailPhys", ctypes.c_ulonglong),')
a('                                ("ullTotalPageFile", ctypes.c_ulonglong),')
a('                                ("ullAvailPageFile", ctypes.c_ulonglong),')
a('                                ("ullTotalVirtual", ctypes.c_ulonglong),')
a('                                ("ullAvailVirtual", ctypes.c_ulonglong),')
a('                                ("ullAvailExtendedVirtual", ctypes.c_ulonglong)]')
a('                m = MEMSTAT(dwLength=ctypes.sizeof(MEMSTAT))')
a('                ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(m))')
a('                self.system_available_mb = m.ullAvailPhys / 1024 / 1024')
a('                total_mb = m.ullTotalPhys / 1024 / 1024')
a('                self.system_used_percent = (1 - self.system_available_mb / total_mb) * 100')
a('            except Exception:')
a('                pass')
a('')
a('    def _poll_loop(self):')
a('        while self._running:')
a('            self._read_memory()')
a('            self.rss_history.append((time.monotonic(), self.current_rss_mb))')
a('')
a('            old_state = self.state')
a('            rss_exceeded = self.current_rss_mb > self.max_rss_mb')
a('')
a('            if self.system_used_percent > self.critical_percent or rss_exceeded:')
a('                self.state = "critical"')
a('                if old_state != "critical":')
a('                    detail = f"RSS={self.current_rss_mb:.0f}MB sys={self.system_used_percent:.0f}%"')
a('                    self.events.append((time.monotonic(), "critical", detail))')
a('                    logger.error(f"Memory CRITICAL: {detail}")')
a('                    # Force garbage collection')
a('                    import gc')
a('                    gc.collect()')
a('                    if self.on_critical:')
a('                        try:')
a('                            self.on_critical()')
a('                        except Exception as e:')
a('                            logger.error(f"Critical callback failed: {e}")')
a('')
a('            elif self.system_used_percent > self.warn_percent:')
a('                self.state = "warn"')
a('                if old_state == "ok":')
a('                    detail = f"RSS={self.current_rss_mb:.0f}MB sys={self.system_used_percent:.0f}%"')
a('                    self.events.append((time.monotonic(), "warn", detail))')
a('                    logger.warning(f"Memory WARNING: {detail}")')
a('            else:')
a('                self.state = "ok"')
a('')
a('            time.sleep(self.poll_interval)')
a('')
a('    def start(self):')
a('        self._running = True')
a('        self._thread = threading.Thread(target=self._poll_loop, daemon=True, name="memory_watchdog")')
a('        self._thread.start()')
a('')
a('    def stop(self):')
a('        self._running = False')
a('        if self._thread:')
a('            self._thread.join(timeout=5)')
a('')
a('    def get_status(self) -> dict:')
a('        return {')
a('            "state": self.state,')
a('            "process_rss_mb": round(self.current_rss_mb, 1),')
a('            "peak_rss_mb": round(self.peak_rss_mb, 1),')
a('            "max_rss_mb": round(self.max_rss_mb, 1),')
a('            "system_used_percent": round(self.system_used_percent, 1),')
a('            "system_available_mb": round(self.system_available_mb, 1),')
a('            "events": len(self.events),')
a('        }')

print(f"Part 1 (Safety): {len(lines)} lines")
with open('edge_ai_v2.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print("edge_ai_v2.py Part 1 written")
